theme: jekyll-theme-cayman
title: Betty White is No Longer Alive
description: Betty White died on December 31 2021 at the age of 99, just 17 days befpre what would have been her 100th birthday.  She is still America's sweetheart and we will always love her!!
keywords: Betty White,alive,celebrity,Is Betty White Still Alive?
content: Betty White died on December 31 2021 at the age of 99, just 17 days befpre what would have been her 100th birthday.  She is still America's sweetheart and we will always love her!!
icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Betty_White_2010.jpg
