theme: jekyll-theme-cayman
title: Betty White is Dead!
description: Betty White died at the age of 99 on December 31, 2021. She was America's sweetheart and we love her!
keywords: Betty White,alive,celebrity,Is Betty White Still Alive?
content: Betty White died at the age of 99 on December 31, 2021. She was America's sweetheart and we love her!
icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Betty_White_2010.jpg