theme: jekyll-theme-cayman
title: Betty White is Still Alive!
description: Betty White is 99 years old and she is America's sweetheart and we love her!
keywords: Betty White,alive,celebrity,Is Betty White Still Alive?
content: Betty White is 99 years old and she is America's sweetheart and we love her!
icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Betty_White_2010.jpg
